application: hooker
version: 1
runtime: go
api_version: go1

inbound_services:
- warmup

builtins:
- datastore_admin: on
- deferred: on

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static
  secure: never

- url: /admin/
  script: _go_app
  login: admin

- url: /cron/.*
  script: _go_app
  login: admin

- url: /api/admin/
  script: _go_app
  login: admin

- url: /backend/.*
  script: _go_app
  login: admin

- url: /_ah/queue/go/delay
  script: _go_app
  login: admin

- url: /deliver/.*
  script: _go_app
  login: optional

- url: .*
  script: _go_app
  login: required
